// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnR0FBBtRMvurjzzbYP4pvF0vZm9DqIyU',
    appId: '1:68309394433:web:b0fc2ded6d821936874c00',
    messagingSenderId: '68309394433',
    projectId: 'thinknest-a619d',
    authDomain: 'thinknest-a619d.firebaseapp.com',
    storageBucket: 'thinknest-a619d.firebasestorage.app',
    measurementId: 'G-04FYKPN6KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALgrmRR96qX43X8Ym8Uqosqac_vs9Z6v8',
    appId: '1:68309394433:android:221ad2d0d473bda5874c00',
    messagingSenderId: '68309394433',
    projectId: 'thinknest-a619d',
    storageBucket: 'thinknest-a619d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvK0p0G1tOcB7Pz6lynqv_h2pWTqWY7g',
    appId: '1:68309394433:ios:3ae5209f82022a87874c00',
    messagingSenderId: '68309394433',
    projectId: 'thinknest-a619d',
    storageBucket: 'thinknest-a619d.firebasestorage.app',
    iosBundleId: 'com.example.thinknest',
  );
}
